-- List of plugins to load with lazy.nvim
return {
  require('plugins.guess-indent'),
  require('plugins.gitsigns'),
  require('plugins.which-key'),
  require('plugins.tmux-navigator'),
  require('plugins.nerdtree'),
  require('plugins.auto-save'),
  require('plugins.copilot'),
  require('plugins.zen-mode'),
  require('plugins.harpoon'),
  require('plugins.telescope'),
  require('plugins.neogit'),
  require('plugins.lazydev'),
  require('plugins.lspconfig'),
  require('plugins.conform'),
  require('plugins.blink-cmp'),
  require('plugins.tokyonight'),
  require('plugins.todo-comments'),
  require('plugins.mini'),
  require('plugins.treesitter'),
}
